apiVersion: apps/v1
kind: Deployment
metadata:
  name: cityos-web
spec:
  selector:
    matchLabels:
      app: cityos-web
  template:
    metadata:
      labels:
        app: cityos-web  # the label for the pods and the deployments
    spec:
      containers:
      - name: cityos-web
        image: acrcityos.azurecr.io/cityos-web:v1.21 # IMPORTANT: update with your own repository
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 # the application listens to this port
#        env:
#        - name: API # the application expects to connect to the API at this endpoint
#          value: http://cityos-cloud.cityos.svc.cluster.local
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 512Mi
      imagePullSecrets:
      - name: acr
